#!/bin/bash

#$ -r y
#$ -q gpu@qa-xp*
#$ -N CW_Test
#$ -pe smp 4
#$ -l gpu=1
#$ -t 1-3

fsync $SGE_STDOUT_PATH &

# python test_methods.py --model QLeNet --dev_var 0.0 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method LM
# python test_methods.py --model QLeNet --dev_var 0.0 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method FGSM
# python test_methods.py --model QLeNet --dev_var 0.0 --attack_c 1e-8 --attack_lr 3e-9 --header $SGE_TASK_ID --method Simple
python test_methods.py --model QLeNet --dev_var 0.0 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method PGD

# python test_methods.py --model QCIFAR --dataset CIFAR10 --dev_var 0.0 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method LM
# python test_methods.py --model QCIFAR --dataset CIFAR10 --dev_var 0.0 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method FGSM
# python test_methods.py --model QCIFAR --dataset CIFAR10 --dev_var 0.0 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method PGD

# python test_methods.py --model QRes18 --dataset CIFAR10 --dev_var 0.0 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method LM
# python test_methods.py --model QRes18 --dataset CIFAR10 --dev_var 0.0 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method FGSM
# python test_methods.py --model QRes18 --dataset CIFAR10 --dev_var 0.0 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method PGD

# python test_methods.py --model QTIN --dataset TinyImageNet --nb_classes 200 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method LM
# python test_methods.py --model QTIN --dataset TinyImageNet --nb_classes 200 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method FGSM
# python test_methods.py --model QTIN --dataset TinyImageNet --nb_classes 200 --attack_c 1e-8 --attack_lr 5e-3 --header $SGE_TASK_ID --method PGD

# python train_admm.py --model QCIFAR --dataset CIFAR10 --train_epoch 200 --dev_var 0.0 --attack_c 1e-7 --attack_lr 3e-5 --attack_w_lr 1e-4 --attack_start 10 --train_var 0

# python train_admm.py --model QRes18 --dataset CIFAR10 --train_epoch 200 --dev_var 0.0 --attack_c 1e-9 --attack_lr 1e-3 --attack_w_lr 0 --attack_start 100

# python train_admm_BN.py --model QRes18 --dataset CIFAR10 --train_epoch 2 --dev_var 0.0 --attack_c 1e-9 --attack_lr 1e-3 --attack_w_lr 0 --attack_start 1

# python train_admm_BN.py --model QTIN --dataset TinyImageNet --nb_classes 200 --train_epoch 200 --dev_var 0.0 --attack_c 1e-6 --attack_lr 1e-5 --attack_w_lr 1e-6 --attack_start 100

# python train_admm.py --model QTIN --dataset TinyImageNet --nb_classes 200 --train_epoch 200 --dev_var 0.0 --attack_c 1e-7 --attack_lr 5e-4 --attack_w_lr 0 --attack_start 150
